version: '3.8'

services:
    app:
        image: laravel-booking-challenge
        container_name: laravel-app
        ports:
            - "8000:8000"   # Expose port 8000 for Laravel app
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret@santa
            MYSQL_DATABASE: booking
            MYSQL_USER: solutech
            MYSQL_PASSWORD: secret@santa # Persist MySQL data
        ports:
            - "3356:3306"  # Expose MySQL on port 3306
        networks:
            - app-network

volumes:
    mysql-data:   # Volume for persisting MySQL data

networks:
    app-network:
        driver: bridge
